const { withDangerousMod, withXcodeProject } = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Ships our own native sources inside the brownfield artifacts, so the typed
 * bridge lives in RepoSearchKit.xcframework / reposearchkit.aar instead of
 * being reimplemented by every host app.
 *
 * `ios/` and `android/` are regenerated by `expo prebuild`, so the sources are
 * kept under `native/` and linked back in on every prebuild.
 */

/**
 * Links one `native/` source into a generated project directory.
 *
 * A symlink rather than a copy: the generated file is what Xcode and Android
 * Studio show as a member of the target, so editing it there has to write
 * through to `native/` — a copy would be silently discarded by the next
 * prebuild.
 */
const linkSource = (sourcePath, destinationPath) => {
  const existing = fs.lstatSync(destinationPath, { throwIfNoEntry: false });

  if (existing?.isFile()) {
    // Not a link: an editor replaced it while saving, or an older prebuild
    // copied it. Either way it may hold edits that only exist here.
    const isSameContent =
      fs.readFileSync(destinationPath, 'utf8') === fs.readFileSync(sourcePath, 'utf8');
    if (!isSameContent) {
      throw new Error(
        `${destinationPath} is a regular file and differs from ${sourcePath}.\n` +
          'It looks like it was edited in place. Copy the changes back into native/ ' +
          'and delete the file, then run prebuild again.'
      );
    }
  }

  fs.rmSync(destinationPath, { force: true });
  fs.symlinkSync(sourcePath, destinationPath);
};

/** pbxproj stores names quoted (`"RepoSearchKit"`), so compare unquoted. */
const unquote = (value) => (typeof value === 'string' ? value.replace(/^"|"$/g, '') : value);

/**
 * iOS needs the file registered in the Xcode project, not just placed on disk.
 *
 * Mods run in reverse registration order (each mod runs its own action, then
 * calls the previously registered one), so this must be listed *before*
 * `expo-brownfield` in the plugins array in order to run *after* it — the
 * target and its group have to exist already.
 */
const withIosSources = (config, { targetName, sources }) => {
  return withXcodeProject(config, (config) => {
    const project = config.modResults;
    const projectRoot = config.modRequest.projectRoot;
    const groupPath = path.join(projectRoot, 'ios', targetName);

    const target = Object.entries(project.pbxNativeTargetSection()).find(
      ([key, value]) => !key.endsWith('_comment') && unquote(value.name) === targetName
    );
    if (!target) {
      throw new Error(
        `expo-brownfield target "${targetName}" not found. Is withRepoSearchBridge listed before expo-brownfield in app.json?`
      );
    }
    const [targetUuid] = target;

    const groupKey =
      project.findPBXGroupKey({ name: targetName }) ??
      project.findPBXGroupKey({ name: `"${targetName}"` });
    if (!groupKey) {
      throw new Error(`Xcode group "${targetName}" not found.`);
    }

    // The framework target's compile-sources phase is registered under the
    // target name rather than the usual "Sources" comment, so
    // `addSourceFile()` cannot find it and would silently attach the file to
    // the app target instead. Resolve the phase from the target itself.
    const sourcesSection = project.hash.project.objects.PBXSourcesBuildPhase;
    const phaseRef = (project.pbxNativeTargetSection()[targetUuid].buildPhases ?? []).find(
      (phase) => sourcesSection[phase.value] !== undefined
    );
    if (!phaseRef) {
      throw new Error(`No compile-sources build phase on target "${targetName}".`);
    }
    const sourcesPhase = sourcesSection[phaseRef.value];

    for (const source of sources) {
      const fileName = path.basename(source);
      linkSource(path.join(projectRoot, source), path.join(groupPath, fileName));

      // The group carries the directory path, so the reference is just the
      // basename — passing `<target>/<file>` would resolve to <target>/<target>/<file>.
      const file = project.addFile(fileName, groupKey, { target: targetUuid });
      if (!file) {
        throw new Error(`${fileName} is already referenced by the Xcode project.`);
      }

      file.uuid = project.generateUuid();
      file.target = targetUuid;
      project.addToPbxBuildFileSection(file);
      sourcesPhase.files.push({ value: file.uuid, comment: `${fileName} in Sources` });
    }

    return config;
  });
};

/**
 * Android picks sources up by directory convention, so dropping the file into
 * the library module's package directory is all that is needed — no Gradle or
 * project file to touch, and the ordering against expo-brownfield's own mods
 * does not matter.
 */
const withAndroidSources = (config, { libraryName, packageName, sources }) => {
  return withDangerousMod(config, [
    'android',
    (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const packageDir = path.join(
        projectRoot,
        'android',
        libraryName,
        'src/main/java',
        ...packageName.split('.')
      );
      fs.mkdirSync(packageDir, { recursive: true });

      for (const source of sources) {
        linkSource(
          path.join(projectRoot, source),
          path.join(packageDir, path.basename(source))
        );
      }

      return config;
    },
  ]);
};

const withRepoSearchBridge = (config, { ios, android }) => {
  if (ios) {
    config = withIosSources(config, ios);
  }
  if (android) {
    config = withAndroidSources(config, android);
  }
  return config;
};

module.exports = withRepoSearchBridge;
