#!/bin/bash
#
# Lints the Swift sources with swift-format, which ships with Xcode — no extra
# tooling to install. Pass --fix to rewrite the files in place.
#
#   ./scripts/swift-format.sh
#   ./scripts/swift-format.sh --fix

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Every hand-written Swift source. expo-app/ios is generated by `expo prebuild`
# and only references native/ios, so it is not listed here.
SOURCES=(
  expo-app/native/ios
  ios-host/HostApp
  ios-host/HostAppTests
)

if [[ "${1:-}" == "--fix" ]]; then
  xcrun swift-format format --in-place --recursive "${SOURCES[@]}"
  echo "swift-format: formatted ${SOURCES[*]}"
else
  xcrun swift-format lint --recursive --strict "${SOURCES[@]}"
  echo "swift-format: no issues in ${SOURCES[*]}"
fi
